// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON("package.json"),
      uglify: {
        my_target: {
          files: {
            'build/<%= pkg.name %>.min.js': ['public/js/admin/*.js', 'public/js/admin/configs/*.js', 'public/js/admin/app/*.js', 'public/js/admin/core/*.js']
          }
        },
        options: {
          banner: "/*! <%= pkg.name %> <%= grunt.template.today(\"yyyy-mm-dd\") %> */\n"
        }
      }
    });
    grunt.loadNpmTasks("grunt-contrib-uglify");
    return grunt.registerTask("default", ["uglify"]);
  };

}).call(this);
